# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0002_auto_20170109_1906'),
        ('unbsolidaria', '0002_auto_20170110_0506'),
    ]

    operations = [
    ]
