# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0003_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='dias',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
    ]
