# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0004_auto_20170111_0241'),
        ('unbsolidaria', '0004_auto_20170111_0245'),
    ]

    operations = [
    ]
