# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('descricao', models.TextField(max_length=140)),
                ('data', models.DateField()),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalho', to='unbsolidaria.Trabalho')),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
